### ISSUE TITLE
指导一下，gpt4-web 无法链接copilot-to-gpt4？

### ISSUE THREAD

**Issue by davidxiao** [aaamoon/copilot-gpt4-service#115]
按下面docker-compose.yml启动后，
可以通过浏览器单独访问两个services，但从gpt4-web提问题时，提示下面错误

{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 4001
  }
}

// docker-compose.yml
version: "3.9"
services:
  copilot:
    container_name: copilot-to-gpt4
    image: aaamoon/copilot-gpt4-service:latest
    environment:
      HOST: 0.0.0.0
      CACHE: true
    ports:
      - "4001:8080"
    restart: always
  web:
    container_name: gpt4-web
    image: yidadaa/chatgpt-next-web:latest
    environment:
      OPENAI_API_KEY: xxx
      BASE_URL: http://127.0.0.1:4001
    ports:
      - "4002:3000"
    restart: always

**Comment by guoyingtao** [comment]
我也遇到了同样的问题，用@dw763j 提供的方案解决了

**Comment by davidxiao** [comment]
// 像下面这样吗？还是不行，得到一样的错误，
hi, @guoyingtao 能分享一下你的配置吗？谢谢

version: "3.9"

services:
  copilot:
    container_name: copilot-to-gpt4
    image: aaamoon/copilot-gpt4-service:latest
    environment:
      HOST: 0.0.0.0
      CACHE: true
    ports:
      - "127.0.0.1:4001:8080"
    restart: always
  web:
    container_name: gpt4-web
    image: yidadaa/chatgpt-next-web:latest
    environment:
      OPENAI_API_KEY: xxx
      BASE_URL: http://127.0.0.1:4001
    ports:
      - "4002:3000"
    restart: always

**Comment by dw763j** [comment]
``` yml
version: "3.9"

services:

copilot:
container_name: copilot-to-gpt4
image: aaamoon/copilot-gpt4-service:latest
environment:
HOST: 0.0.0.0
CACHE: true
ports:
- "【你的局域网ip地址，如192.168.1.45】:4001:8080"
restart: always

web:
container_name: gpt4-web
image: yidadaa/chatgpt-next-web:latest
environment:
OPENAI_API_KEY: xxx
BASE_URL: http://【你的局域网ip地址，如192.168.1.45】:4001/
ports:
- "【你的局域网ip地址，如192.168.1.45】:4002:3000"
restart: always
```

**Comment by dw763j** [comment]
> // 像下面这样吗？还是不行，得到一样的错误， hi, @guoyingtao 能分享一下你的配置吗？谢谢
> 
> version: "3.9"
> 
> services: copilot: container_name: copilot-to-gpt4 image: aaamoon/copilot-gpt4-service:latest environment: HOST: 0.0.0.0 CACHE: true ports: - "127.0.0.1:4001:8080" restart: always web: container_name: gpt4-web image: yidadaa/chatgpt-next-web:latest environment: OPENAI_API_KEY: xxx BASE_URL: http://127.0.0.1:4001 ports: - "4002:3000" restart: always

``` yml
version: "3.9"

services:

copilot:
container_name: copilot-to-gpt4
image: aaamoon/copilot-gpt4-service:latest
environment:
HOST: 0.0.0.0
CACHE: true
ports:
- "【你的局域网ip地址，如192.168.1.45】:4001:8080"
restart: always

web:
container_name: gpt4-web
image: yidadaa/chatgpt-next-web:latest
environment:
OPENAI_API_KEY: xxx
BASE_URL: http://【你的局域网ip地址，如192.168.1.45】:4001/
ports:
- "【你的局域网ip地址，如192.168.1.45】:4002:3000"
restart: always
```
