### ISSUE TITLE
null pre- and postfix on Chatbox client

### ISSUE THREAD

**Issue by bitfl0wer** [aaamoon/copilot-gpt4-service#121]
### Description

I set up this service using docker compose using the following docker-compose.yml

```yml
version: '3'

services:
  copilot-gpt4-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - 4780:8080
    restart: unless-stopped
    container_name: copilot-gpt4-service
```

Because I do not want to use Vercel, I decided to use the Chatbox client. This seems to work great, even with GPT4, however, API-request results seem to be pre- and postfixed with `null`, like in the image below.

<img width="1277" alt="Screenshot depicting the Chatbox client and a ChatGPT conversation 'nullChatbot Intronull'." src="https://github.com/aaamoon/copilot-gpt4-service/assets/39242991/f6d67642-5075-4e53-80cc-948730e56aac">

Edit: The following settings are being used in the Chatbox client:

<img width="575" alt="grafik" src="https://github.com/aaamoon/copilot-gpt4-service/assets/39242991/204586c1-1f26-4ad4-89e3-fcbfc79c54af">
