### ISSUE TITLE
Add Memory Requirement in README.md

### ISSUE THREAD

**Issue by windy32** [aaamoon/copilot-gpt4-service#305]
### Description

Some users deploy the service on Cloud. They just have a site with public domain, and nginx and SSL have been configured before.

However, such sites may be running on very small VMs (e.g., less than 1GB momory).

Today I notice that copilot-gpt4-service requires a lot of memory when running docker compose up.

It's a good idea to list the memory requirements for popular server OS in README.md:
 - Ubuntu Server 20.04 / 22.04
 - CentOS
 - Debian

### Why

-

### Alternatives

Just buy bigger VM instances

**Comment by Geniucker** [comment]
So what's the exact number of "a lot of"

**Comment by windy32** [comment]
> So what's the exact number of "a lot of"

It is hard to run docker compose up on a VM with about 600 MB memory

**Comment by Geniucker** [comment]
Got it. I guess the  reason is that current docker-compose.yml have to build before actually running the container. After the container started up, the memory usage should be no more than 20MB I guess.
We're gonna modify the docker-compose.yml

**Comment by Geniucker** [comment]
Can you try this docker-compose.yml

```yaml
version: '3.8'

services:
  copilot-gpt4-service:
    image: aaamoon/copilot-gpt4-service:latest
    environment:
      - HOST=0.0.0.0
      #- COPILOT_TOKEN=gnu_xxxxx
      #- SUPER_TOKEN=your_super_token
      #- ENABLE_SUPER_TOKEN=false
      #- RATE_LIMIT=1000
    ports:
      - 8080:8080
    restart: unless-stopped
    container_name: copilot-gpt4-service
    command: ["-log_level", "info"]
```
